from fastapi import FastAPI, Depends, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
import pandas as pd
from sqlalchemy.orm import Session
import os

from services.math_engine import calculate_spend_velocity, calculate_savings_velocity
from services.advisor import generate_insight
from database import get_db, engine
import models
import schemas
from typing import List

# Create all database tables based on our models if they don't exist
models.Base.metadata.create_all(bind=engine)

import firebase_admin
from firebase_admin import auth, credentials

# Initialize Firebase Admin
try:
    if not firebase_admin._apps:
        # It expects GOOGLE_APPLICATION_CREDENTIALS to be set
        firebase_admin.initialize_app()
except Exception as e:
    print("Warning: Firebase Admin not initialized correctly.", e)


app = FastAPI(title="Artha API", description="Backend for Artha Personal CFO MVP")

# Secure CORS config
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # Update to your Firebase Hosting URLs in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

security = HTTPBearer()

def verify_firebase_token(credentials: HTTPAuthorizationCredentials = Depends(security)):
    """Middleware to verify Firebase JWT tokens on secured routes."""
    token = credentials.credentials
    try:
        # Validating the actual Firebase Token sent from the frontend
        decoded_token = auth.verify_id_token(token)
        return decoded_token
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid authentication credentials",
            headers={"WWW-Authenticate": "Bearer"},
        )

@app.get("/api/insights")
def get_insights(user: dict = Depends(verify_firebase_token), db: Session = Depends(get_db)):
    """Secured route to fetch user financial insights generated by Vertex AI."""
    
    # Fetch real user by Firebase UID
    db_user = db.query(models.User).filter(models.User.firebase_uid == user["uid"]).first()
    
    if not db_user:
        # For MVP, auto-create user on first login
        new_user = models.User(firebase_uid=user["uid"], email=user.get("email", "unknown@email.com"))
        db.add(new_user)
        db.commit()
        db.refresh(new_user)
        db_user = new_user

    # Fetch real transaction data into Pandas DataFrame
    query = db.query(models.Transaction).filter(models.Transaction.user_id == db_user.user_id).statement
    df_transactions = pd.read_sql(query, db.bind)
    
    budget_limit = 2000.0
    required_monthly_savings = 500.0
    available_cash_flow = 600.0
    
    spend_velocity = calculate_spend_velocity(df_transactions, budget_limit)
    savings_velocity = calculate_savings_velocity(available_cash_flow, required_monthly_savings)
    
    # --- SMARTER AI: Aggregate real spending by category ---
    category_spending = {}
    if not df_transactions.empty and 'category' in df_transactions.columns:
        # Group by category, sum amounts, and round to 2 decimal places
        category_totals = df_transactions.groupby('category')['amount'].sum().round(2)
        category_spending = category_totals.to_dict()
    
    financial_data = {
        "spend_velocity": spend_velocity,
        "savings_velocity": savings_velocity,
        "available_cash_flow": available_cash_flow,
        "total_spent": round(df_transactions['amount'].sum(), 2) if not df_transactions.empty else 0,
        "budget_limit": budget_limit,
        "category_spending": category_spending,
        "num_transactions": len(df_transactions),
    }
    
    insight = generate_insight(financial_data)
    
    return {
        "uid": user["uid"],
        "insights": insight,
        "metrics": financial_data
    }

@app.post("/api/transactions", response_model=schemas.TransactionResponse)
def create_transaction(transaction: schemas.TransactionCreate, user: dict = Depends(verify_firebase_token), db: Session = Depends(get_db)):
    db_user = db.query(models.User).filter(models.User.firebase_uid == user["uid"]).first()
    if not db_user:
        db_user = models.User(firebase_uid=user["uid"], email=user.get("email", "unknown@email.com"))
        db.add(db_user)
        db.commit()
        db.refresh(db_user)
        
    new_tx = models.Transaction(**transaction.model_dump(), user_id=db_user.user_id)
    db.add(new_tx)
    db.commit()
    db.refresh(new_tx)
    return new_tx

@app.get("/api/transactions", response_model=List[schemas.TransactionResponse])
def get_transactions(user: dict = Depends(verify_firebase_token), db: Session = Depends(get_db)):
    db_user = db.query(models.User).filter(models.User.firebase_uid == user["uid"]).first()
    if not db_user:
        return []
        
    txs = db.query(models.Transaction).filter(models.Transaction.user_id == db_user.user_id).order_by(models.Transaction.transaction_date).all()
    return txs

@app.post("/api/goals", response_model=schemas.GoalResponse)
def create_goal(goal: schemas.GoalCreate, user: dict = Depends(verify_firebase_token), db: Session = Depends(get_db)):
    db_user = db.query(models.User).filter(models.User.firebase_uid == user["uid"]).first()
    if not db_user:
        raise HTTPException(status_code=404, detail="User not found")
        
    new_goal = models.FinancialGoal(**goal.model_dump(), user_id=db_user.user_id)
    db.add(new_goal)
    db.commit()
    db.refresh(new_goal)
    return new_goal

@app.get("/api/goals", response_model=List[schemas.GoalResponse])
def get_goals(user: dict = Depends(verify_firebase_token), db: Session = Depends(get_db)):
    db_user = db.query(models.User).filter(models.User.firebase_uid == user["uid"]).first()
    if not db_user:
        return []
    goals = db.query(models.FinancialGoal).filter(models.FinancialGoal.user_id == db_user.user_id).all()
    return goals
